### ISSUE TITLE
scrub on timeline, focus should stay on timeline

### ISSUE THREAD

**Issue by mestela** [animanathome/movemebugs#11]
when scrubbing the timeline, your eye is on the animation, not the timeline. its easy for the cursor to drift off the timeline, but this should continue to scrub, not lose focus as it does now.

**Comment by animanathome** [comment]
A version of this has been implemented and will be released tomorrow evening (pacific timezone).

**Comment by animanathome** [comment]
This has now been released. Please let me know if we can close the ticket.

**Comment by mestela** [comment]
yep, fixed! thanks.
