### ISSUE TITLE
duplicate anim curves

### ISSUE THREAD

**Issue by ambreAtGithub** [animanathome/movemebugs#13]
Importing the same animation multiple times results in game a doubling up of curves. Here I would expect it to either overwrite or replace the original curves. 

![duplicate_curves](https://cloud.githubusercontent.com/assets/13375393/8740457/c5381536-2bfe-11e5-826c-89272cd36a4b.png)

**Comment by animanathome** [comment]
Ai, that's bad. We'll be addressing this one asap!

**Comment by animanathome** [comment]
This issue has now been addressed an the fix will be released this evening. The updated method will ensure no duplicate animation curves get added to a given object. 

To ensure we can overwrite the animation of a given asset we'll add a new method which will remove any existing animation.

**Comment by animanathome** [comment]
This issue has now been released. Please let me know if I can close the issue.
